main: io.github.at.main
name: AdvancedTeleport
version: 5.0.0
description: A plugin which is based on tons of teleport stuff.
authors: [Niestrat99,Thatsmusic99]
softdepend: [Vault]


commands:
  athelp:
  tpr:
  tpa:
  tpon:
  tpoff: